spring.application.name=apigateway


spring.cloud.config.uri=http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.value}

#configuracion

spring.cloud.gateway.server.webflux.routes[0].id=micro-server-categorias
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CATEGORIAS
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/categorias/**
#spring.cloud.gateway.server.webflux/routes[0].filters[0]=stripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=micro-server-productos
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PRODUCTOS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/productos/**
